# Generated by Django 4.2 on 2023-04-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_product', models.CharField(choices=[('Mobile', 'mobile'), ('tv', 'tv'), ('ac', 'ac')], max_length=50)),
                ('available', models.BooleanField()),
                ('number_of_product', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
