# Generated by Django 4.2 on 2023-04-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='product_model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
