# Generated by Django 4.2 on 2023-04-19 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_detail_product_model_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_detail',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='product_detail',
            name='company_product',
        ),
        migrations.RemoveField(
            model_name='product_detail',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='product_detail',
            name='product_model_name',
        ),
        migrations.AddField(
            model_name='product_detail',
            name='product_company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('product_image', models.ImageField(upload_to='media')),
                ('product_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product_detail')),
            ],
        ),
    ]
