# Generated by Django 4.2 on 2023-04-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_detail_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.DeleteModel(
            name='Product_detail',
        ),
    ]
