# Generated by Django 4.2 on 2023-04-19 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_list_delete_phone_delete_product_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grocery_item', models.CharField(choices=[('Staples', 'Steples'), ('Snacks & Beverages', 'Snacks & Beverages'), ('Packaged Food', 'Packaged Food'), ('Personal & Baby Care', 'Personal & Baby Care'), ('Household Care', 'Household Care'), ('Dairy & Eggs', 'Dairy & Eggs'), ('Home & Kitchen', 'Home & Kitchen')], max_length=20)),
                ('available', models.BooleanField()),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product_list')),
            ],
        ),
    ]
