# Generated by Django 4.2 on 2023-04-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer_details',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='BUYER'),
        ),
    ]
