# Generated by Django 4.2 on 2023-04-17 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_alter_buyer_details_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buyer_Details',
            new_name='Buyer_Detail',
        ),
    ]
