# Generated by Django 4.2 on 2023-04-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_rename_buyer_details_buyer_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer_detail',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
