# Generated by Django 4.2 on 2023-04-18 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_alter_buyer_detail_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer_detail',
            options={'verbose_name_plural': 'Buyer'},
        ),
    ]
