# Generated by Django 4.2 on 2023-04-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_alter_buyer_detail_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer_city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('Buyer_Detail', models.ManyToManyField(to='buyer.buyer_detail')),
            ],
        ),
    ]
