# Generated by Django 4.2 on 2023-04-24 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_buyer_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer_detail',
            name='Date_of_birth',
        ),
    ]
