# Generated by Django 4.2 on 2023-04-18 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Home_Detail',
        ),
        migrations.AlterModelOptions(
            name='home_detail',
            options={'verbose_name_plural': 'Home'},
        ),
    ]
