# Generated by Django 4.2 on 2023-04-18 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_home_home_detail_alter_home_detail_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home_detail',
            name='phone',
        ),
    ]
