# Generated by Django 4.2 on 2023-04-18 07:19

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_home_detail_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_detail',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=10, null=True),
        ),
    ]
