# Generated by Django 4.2 on 2023-04-18 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_home_detail_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home_detail',
            name='files',
        ),
    ]
