# Generated by Django 4.2 on 2023-04-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_home_detail_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_detail',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
